### ISSUE TITLE
Unable to call 'render'

### ISSUE THREAD

**Issue by benmyles** [MrRobb/gym-rs#14]
Getting the following error:

```
$ cargo run --example basic
thread 'main' panicked at 'Unable to call 'render': PyErr { ptype: <class 'TypeError'>, pvalue: Some(TypeError('item 1 in _argtypes_ passes a union by value, which is unsupported.')), ptraceback: Some(<traceback object at 0x7f9d9ff248c0>) }', src/libcore/result.rs:1165:5
```

This only happens when `render` is `true`: with rendering disabled everything works correctly.

My python `gym` version is `0.12.5` and python itself is `Python 3.7.6`. Is there a known combination of gym/python versions that work?

**Comment by benmyles** [comment]
Turns out ~this is an issue with python 3.8 -- cpython was not picking up my `pyenv` version and instead using my system python install.

**Update:** I got cypthon to use python 3.7.6 but same error.

**Comment by MrRobb** [comment]
I will have a look at it tonight.

**Comment by MrRobb** [comment]
The issue might be with the version of the gym module. I have version 0.15.4 and it renders correctly.

**Comment by benmyles** [comment]
Looks like it's working fine on my Ubuntu box with gym 0.15.4 and Python 3.7.5. Can probably close this. Thanks!
